[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qrm5husws0a3lzgfll7v23h768lacw3c9xmz8h0xunkg48rt5rjsxcej4u2"]

[[validator_account]]
address = "tnam1qytuqrevscq0v3d4ctn7zsm4qva2x3n7hqra8llg"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.108.76.60:36656"

[validator_account.consensus_key]
pk = "tpknam1qpc7z2d3g6gfmet4dakp58zjus4axzxxmcsdqk80epeycg6nckkq27qraa7"
authorization = "signam1qznkesw3gfucc5ulw93rrhmtlukgh6sff2t5g82at7em4uplksng8084chh2rg7xxkf3zvfa3yvzedyvcghg4kghvgsu9shz0xng99q00fcq2g"

[validator_account.protocol_key]
pk = "tpknam1qznlzqvt2zvyqe5yvdpgz9xg6mss79yefeyhs9w4y72r08krdsxmc689hxc"
authorization = "signam1qz8tqvvpwlpfm006nmfsfy9njf5636qrlgvwfc7glhvpk3e8x2wad7n950ghndkmvs8nxn2awzu4jy3q8jmx6a8hqg683220q8xs22s24ky2zc"

[validator_account.tendermint_node_key]
pk = "tpknam1qqzzjdpa7akx4c0gdcgakccu5wcss2ewgekqxxlsj6udlk2nytprclm0ptm"
authorization = "signam1qqn62yhluv0ylljhymfmcsp8sgqlprua4zjlnqu4p3mzl449myl3h749fv4aphcny4hh5un4x3mv3z5ztr97sxzz39u3jc78t5jzfmqpe8q3v9"

[validator_account.eth_hot_key]
pk = "tpknam1qypyhefz84wy023gufjvp4yjfze86lajv8xudj0tccmrhhwrkkje5mqztkfp7"
authorization = "signam1q9uqez9d8f0k5v9dx74x9f5nc6gy5arsx8wvmev8m0hx3dc9v9q2vsgqcny3wja2l4wmcep3fjzq7xgadpvmenfggka3wmthuf8knqzhqyc7uqwk"

[validator_account.eth_cold_key]
pk = "tpknam1qyp8pugvcelzhev6d53q9myekt7x0jnpgjq4n3847fclk4hrcddfeqq2euq7w"
authorization = "signam1q93xf6yrktuc3evp9fdaakev63xfh7hpmm7hwyte90tm3mmzjyhxv3cgen3uh62gvrvrr6f5khrwtmxurgxpk67v5f7k5w8nzxv7rpyeqqnq9xnr"

[validator_account.metadata]
email = "validators@bwarelabs.com"
description = "Guaranteed availability and up-time backed by a professional blockchain infrastructure team."
website = "https://bwarelabs.com"
discord_handle = "kristianbwarelabs.com"

[validator_account.signatures]
tpknam1qrm5husws0a3lzgfll7v23h768lacw3c9xmz8h0xunkg48rt5rjsxcej4u2 = "signam1qp88mgrcmm32eagus7lz6dae5ajjj0gmsramth25l38mep3q7fn2tf0j5mqj47sdelafsumdhp22supuwar9jzn023yjdgexye9hzfqfn2mau4"

[[bond]]
source = "tnam1qytuqrevscq0v3d4ctn7zsm4qva2x3n7hqra8llg"
validator = "tnam1qytuqrevscq0v3d4ctn7zsm4qva2x3n7hqra8llg"
amount = "2631540"

[bond.signatures]
tpknam1qrm5husws0a3lzgfll7v23h768lacw3c9xmz8h0xunkg48rt5rjsxcej4u2 = "signam1qrhctgpc6fukuefnk6xexzsg8y2uh7446ywzn7fnp8wga4dh3rzhcsl4jske6h4c7c7dj09uy3h2atvstwlgk48wlktqkqlmcxjr5lcr63yjsc"
