[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qr7t9uh2lpcx53hqkdzmwjwsw9004et2vqqajz0yn0c20zwxkx3rx57vm2w"]

[[validator_account]]
address = "tnam1q8k3n8s8kxru59rv5elrcet04r8py82jmcw3m8cl"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.5"
net_address = "5.199.172.43:26656"

[validator_account.consensus_key]
pk = "tpknam1qrggzk6j8x28wu7st6326zj4yk62jjs50gw06l3qygxm59zn4xhlgmy8jue"
authorization = "signam1qr86ej3zva5fp2e4cdnxc0cfp3hgq3ysc2c4z4eaf5fmckhw3r2rz4prkhyt32xlcdahn6cyavqqqcx2jll2qkkky9ekqfvy7t5phuqxgzl4u4"

[validator_account.protocol_key]
pk = "tpknam1qr7cl9ghn29maqw4tspa0gu7kkf0wa05n9sal48tc8yvvm9t22x5s3a86yz"
authorization = "signam1qp37s8jd9c4drgvxwy3ua04slrugxw8cshu4v494vhj2tdqhpp945nwd3r85lj9j6v9enak4newaect4t29zgsml4wnl3gtkzdv8kuqzym5758"

[validator_account.tendermint_node_key]
pk = "tpknam1qrvyw80fk6n2pg2vd0lskxwt2ac8ekdl4wzlcc35ng3fd998lfnvztvw3rl"
authorization = "signam1qrv2k8eh6vf9axhr5wvs8gr05pnuuw7h0jc65sjppupm3n77f8adsnhqz0t4vsul7xh735yqpdyh0ghmnpq7rwhpj8h4pkgl0y664eqx0ay5xc"

[validator_account.eth_hot_key]
pk = "tpknam1qypgf7sv4yn7rks454kccmzgxcrecmegw7t9exkvgvajrearpavwdusyvcgnz"
authorization = "signam1q9usejcrsntq9n3qaa9phzv7jw7h63swuxdz5mdqd5jfp6xs6f8ssltpg70gqrr34j4px9ll6rgk8rl228gf0t4x0zakj39r3nqdy0sfqy2tau0d"

[validator_account.eth_cold_key]
pk = "tpknam1qypjcxdf5q3q9jkul4cqcwm8hw6g4m42yzdf3rk7kevx7necdx2zucqv6jv8v"
authorization = "signam1qx6acu7k87ml4y5d6s0lmwz7hl5p8x85quqec7jwygaxea5emndl7q47cm2nudu9zfr3j5mr3fk7uyh7f8hqu88aenzvq4vnasl36l6hqyzmu2ze"

[validator_account.metadata]
email = "namada@chainflow.io"
website = "https://chainflow.io"

[validator_account.signatures]
tpknam1qr7t9uh2lpcx53hqkdzmwjwsw9004et2vqqajz0yn0c20zwxkx3rx57vm2w = "signam1qrcctegr96aue5ttnk3s4q0gny98qzrkew748pa376salghdfd6f4emvzptvcfjzq6vtldyeqtxrkss4d2hrsjp4npa6skt9kut0guqy43pz5x"

[[bond]]
source = "tnam1q8k3n8s8kxru59rv5elrcet04r8py82jmcw3m8cl"
validator = "tnam1q8k3n8s8kxru59rv5elrcet04r8py82jmcw3m8cl"
amount = "2630549.707602"

[bond.signatures]
tpknam1qr7t9uh2lpcx53hqkdzmwjwsw9004et2vqqajz0yn0c20zwxkx3rx57vm2w = "signam1qrjehfhuc8hrt9jc83q2u3eusqzcut4eh98fnl7fqynhe4n5ede5x7g2kwyc8w2k69vyjlzmfrwazjuzsyz2zfwzy78n6tpcyrnvv5s97rjaa6"
