[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qz0xsmlf2rzylu870knrnul63tu5602nazf2n0cq0w4ljtzl7923cxvwh5d"]

[[validator_account]]
address = "tnam1qx2vhw6est5z6stfvjjfx4q9kry2w5k3yycjawjw"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "84.247.134.192:26656"

[validator_account.consensus_key]
pk = "tpknam1qp66d92kk5hyz4g4ex6ltecn9r04788xh4yu5fed22lqtv4vzrevueyaq09"
authorization = "signam1qr9rca3l5m5nq8ypvn5kzlak2aq328h0arwn4yjynqtqs8dy7kvm2wyy249wrqedg6njxffpxxzmxlylmup5nqtyyzpv0jc2hktd4zct4s975f"

[validator_account.protocol_key]
pk = "tpknam1qpksa9eajnrzpqhuhzm3gz99r3l7nv3c8te45e4y5aanuehvc3u56daz6ur"
authorization = "signam1qpd56tpjnsxhrsnx08pd3rpx9elhqtckyph4yq6vaj9hn8rjeytnd0fcvd3xhshrlturlv7tzk3rtaep3dgjg8k4d6p4khe5alrk47qqa4vpnn"

[validator_account.tendermint_node_key]
pk = "tpknam1qz54um28cah4fpgag4u7zws6vrdfqfk235hdynpcxkjcd9t0zlm0qddwkqm"
authorization = "signam1qzm5cz4485z07j5glunlfxjnkah0w7hmzvpuaawppyyf6650qq8h3ap680sa2wjrndzya8c9wqzrqaqc5fcw69eg3zd9qedz57xgh8cpp89ecu"

[validator_account.eth_hot_key]
pk = "tpknam1qyp3kl8dpvf5djz0davtleqkdpmptlmyun0vyr894c6g3kmxmvjwcxs2qxfep"
authorization = "signam1q8q83khw8233nnxg09czpg9e0pq49x2u6uce0gvnlyc5skn9mel0xmrhv9le8aqtza0asnla2yxwscz6pp0lamvgtk3yv54s4yv4an6xqqrjmrxf"

[validator_account.eth_cold_key]
pk = "tpknam1qyp68hp3syn9msrpul0ek2qpk4aytdrcpc0fml00vpfc80sk6l7xk5qyvzgeh"
authorization = "signam1qxs6htacs4kerawer5d6ufmjwk699c2pz6dugfj88x4g4prt6x9mvu0c29w20va64g60n6ehlkewpv2ydvt9j4225qfmud3vevzu2futqqvq8k73"

[validator_account.metadata]
email = "bourdeaudhui.julien@gmail.com"
discord_handle = "cryptodruide"
description = "Stake & Be part of the Crypto Universe"
avatar = "https://raw.githubusercontent.com/Crypto-Druide/Crypto_Universe/main/crypto_universe-ok.png"

[validator_account.signatures]
tpknam1qz0xsmlf2rzylu870knrnul63tu5602nazf2n0cq0w4ljtzl7923cxvwh5d = "signam1qr59a0v4dadlq7u9m6jclt70rulrtp6p7wjgdqhrqnl6j94e73lhm43mv526nj2wy2ku956py62qh6ym3xeewv3k3w9ajj4qfznlupc2afnl39"

[[bond]]
source = "tnam1qx2vhw6est5z6stfvjjfx4q9kry2w5k3yycjawjw"
validator = "tnam1qx2vhw6est5z6stfvjjfx4q9kry2w5k3yycjawjw"
amount = "2631049.707602"

[bond.signatures]
tpknam1qz0xsmlf2rzylu870knrnul63tu5602nazf2n0cq0w4ljtzl7923cxvwh5d = "signam1qqkydhx4fjdt5mm567eptzsyds4m7qnakurfgx7srynrr7e7g9mr2g8kehmu4w6xg4d49py7vuj8sg985qhkd5l4fjp5vf7uxynvkysfgruete"
