[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qzaghsgna6ejkfgetxahf5atpn2ykc7xuu5dvj2u5uffxtjf09qvy67flrz"]

[[validator_account]]
address = "tnam1q8j7hv499zz5rl256pkyh9lwzu7n00u69ywz7dpx"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "65.109.117.208:10000"

[validator_account.consensus_key]
pk = "tpknam1qzhqnfkvyk8s2j2sunngm7qt2a88munmu0thhlf8f28335xylphdjshc4wv"
authorization = "signam1qrn26qnx0xzn5e0txtcrgnd9vyruh0qlxhtvg4u5k0g2ce2uxzqfv7nsefd9jsjg75etgz06mc3j9wgv2797cgnwxg9vee4gwp59ancgj33ctl"

[validator_account.protocol_key]
pk = "tpknam1qqw849wrqqkglgw07nmq03vmn7ye2zzt40xt0p7k9jmg54dd9f6855zptgv"
authorization = "signam1qqd26v0h5usaer027gnmk3ycq0xcslk82e4zvtynmchlv3cs6quxd7pddtndht62xtf2ar3vdm5dmkth6y62ys6vmc0r9v8n2qnv5ksgt87w3x"

[validator_account.tendermint_node_key]
pk = "tpknam1qpustredh30ekt0ze8zw3yld68ttq9sm6pp06g09x0mwrh84hurlkx9a39u"
authorization = "signam1qz2l3f82jx9xvys9kynvuky2pkxtu4fdhmk3xacps4kz0zpahhp48m4vtlhtlfljfwfts09fc0u0ad2ecxu3j32n9hudqlqn2fgkemcqs0cgq6"

[validator_account.eth_hot_key]
pk = "tpknam1qypn23zwx9nzgavtzd26m4ydf45a4gjm38vvns07cux694fkq65r2qq7hssmq"
authorization = "signam1qyzm8f765qypxcs29wpmlsu5a78f2m5y04u2s6s3up9gsqu0hg29cfx0ctjzca76pup5yx3ea6uadvz072esllu4ruvr5ry8hxuzc9dfqyt48pml"

[validator_account.eth_cold_key]
pk = "tpknam1qypqqvydxdhtqpaflzw6np6y5k4a7myla3vtr6pvslu45xuh449uyrczc6q3r"
authorization = "signam1qywgrt60hg4tl2ranmd9xr3xhu62pfs34rr0vhf5pkn5sstpt82x68kuclfar77cr23rjfxla53s3lqjwnp3hd69lxvygm4swgcx96lkqqc9uxcq"

[validator_account.metadata]
email = "vinh@notional.ventures"
discord_handle = "vinh2000"

[validator_account.signatures]
tpknam1qzaghsgna6ejkfgetxahf5atpn2ykc7xuu5dvj2u5uffxtjf09qvy67flrz = "signam1qre2x8l02zg3tf3t2ygndd49gnyyly8e06f9aqpjxps570kns57hyhwxwzet2dn9uddjax2q43n6rx9lhdr95uu2ywp3eqeg9s3j2fs9v59y50"

[[bond]]
source = "tnam1q8j7hv499zz5rl256pkyh9lwzu7n00u69ywz7dpx"
validator = "tnam1q8j7hv499zz5rl256pkyh9lwzu7n00u69ywz7dpx"
amount = "2000000"

[bond.signatures]
tpknam1qzaghsgna6ejkfgetxahf5atpn2ykc7xuu5dvj2u5uffxtjf09qvy67flrz = "signam1qpqphz75klkysnn3ntqsp3wyc2l5ua2hsygd6ufhv5m2qztep76znyr5x3rej7j0zdg0d8kj3lqu26jt9lcafzvrq7sh7tg33qjdl6cga6r2hu"
